version: "3.8"
services:
  orchestrator:
    image: suvambasak/orchestrator:latest
    volumes:
      - "~/.ssh:/root/.ssh"
    environment:
      - IP=192.168.0.169
      - PORT=7890
    command: [ "python3", "-u", "/root/agent.py" ]
