version: "3.8"
services:
  orchestrator:
    image: suvambasak/orchestrator:latest
    volumes:
      - "~/.ssh:/root/.ssh"
      - "/tmp/opera_config:/root/.config"
    environment:
      - IP=${IP}
      - PORT=${PORT}
    command: [ "python3", "-u", "/root/agent.py" ]
