---
tosca_definitions_version: tosca_simple_yaml_1_3

description: Service Template for deploying service container on Docker Swarm.

imports:
  - nodetypes/swarm/swarm.yaml
  - nodetypes/service_container/service_container.yaml

metadata:
  template_name: "docker"
  template_author: "UoH"
  template_version: "1.0"

topology_template:
  inputs:
    host_ip:
      type: string
    manager:
      type: list
      default: []
    workers:
      type: list
      default: []
    image:
      type: string
      default: hello-world

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    docker-swarm:
      type: radon.nodes.DockerSwarm
      requirements:
        - host: my-workstation

    service:
      type: radon.nodes.ServiceContainer
      requirements:
        - host: docker-swarm
...