---
tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - nodetypes/docker/docker.yaml
  - nodetypes/pyapp/pyapp.yaml

metadata:
  template_name: "docker"
  template_author: "XLAB"
  template_version: "1.0"

topology_template:
  inputs:
    host_ip:
      type: string

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    docker:
      type: radon.nodes.docker
      requirements:
        - host: my-workstation

    app:
      type: radon.nodes.pyapp
      requirements:
        - host: my-workstation
...