---
tosca_definitions_version: tosca_simple_yaml_1_3

description: Service Template for deploying docker container of a python script.

imports:
  - nodetypes/docker/docker.yaml
  - nodetypes/container/container.yaml

metadata:
  template_name: "docker"
  template_author: "UoH"
  template_version: "1.0"

topology_template:
  inputs:
    host_ip:
      type: string

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    docker-engine:
      type: radon.nodes.Docker
      requirements:
        - host: my-workstation

    app-container:
      type: radon.nodes.Container
      requirements:
        - host: docker-engine
...