---
- hosts: all
  gather_facts: false

  tasks:
    - name: Install package
      shell: ssh pi@{{ item }} "sudo pip3 install Adafruit_DHT"
      loop: "{{ sensor_nodes }}"
    
    - name: Install git
      shell: ssh pi@{{ item }} "sudo apt install git -y"
      loop: "{{ sensor_nodes }}"


    - name: Clone the repository
      shell: ssh pi@{{ item }} "git clone https://github.com/suvambasak/sensor.git"
      loop: "{{ sensor_nodes }}"

    - name: Get the IP address of this machine and register
      shell: echo $(hostname -I) | awk '{print $1}'
      register: ip

    - name: Push configuration
      shell: ssh pi@{{ item }} "echo '{\"pin\":\"4\",\"ip\":\"{{ ip.stdout }}\"}' > ~/sensor/conf.json"
      loop: "{{ sensor_nodes }}"

    - name: Move the service to the system directory
      shell: ssh pi@{{ item }} "sudo mv ~/sensor/dht11.service /etc/systemd/system/dht11.service"
      loop: "{{ sensor_nodes }}"

    - name: Reload the systemctl daemon
      shell: ssh pi@{{ item }} "sudo systemctl daemon-reload"
      loop: "{{ sensor_nodes }}"

    - name: Enable the service
      shell: ssh pi@{{ item }} "sudo systemctl enable dht11.service"
      loop: "{{ sensor_nodes }}"

    - name: Start the service
      shell: ssh pi@{{ item }} "sudo systemctl start dht11.service"
      loop: "{{ sensor_nodes }}"
...