---
- hosts: all
  gather_facts: false
  
  tasks:
    - name: Install package
      shell: ssh pi@{{ item }} "sudo pip3 install rpi.gpio websockets"
      loop: "{{ privileged_nodes }}"

    - name: Get the IP address of this machine and register
      shell: echo $(hostname -I) | awk '{print $1}'
      register: ip

    - name: Start privileged container
      shell: ssh pi@{{ item }} "docker container run --rm --privileged -v /sys:/sys -v /usr:/usr -d -e IP={{ ip.stdout }} --name {{ container_name }} {{ image_name }}"
      loop: "{{ privileged_nodes }}"
        
...