---
tosca_definitions_version: tosca_simple_yaml_1_3

description: Service Template for deploying remote LED service in swarm

imports:
  - nodetypes/swarm/swarm.yaml
  - nodetypes/service_container/service_container.yaml
  - nodetypes/actuation_service/actuation_service.yaml

metadata:
  template_name: "docker"
  template_author: "UoH"
  template_version: "1.0"

topology_template:
  inputs:
    host_ip:
      type: string
      
    manager:
      type: list
      default: []
    workers:
      type: list
      default: []

    actuators:
      type: list
      default: []

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    docker-swarm:
      type: radon.nodes.DockerSwarm
      requirements:
        - host: my-workstation

    web-server:
      type: radon.nodes.ServiceContainer
      properties:
        container_name: nginx
        image_name: suvambasak/webpage:websocketled
        published_port: 80
        target_port: 80
        replicas: 1
      requirements:
        - host: docker-swarm

    python-websocket-server:
      type: radon.nodes.ServiceContainer
      properties:
        container_name: websocket_server
        image_name: suvambasak/pyimg:websocketledserver
        published_port: 7890
        target_port: 7890
        replicas: 1
      requirements:
        - host: docker-swarm

    led-actuators:
      type: radon.nodes.ActuationService
      requirements:
        - host: my-workstation
        - dependency: python-websocket-server
...