---
tosca_definitions_version: tosca_simple_yaml_1_3

description: Service Template for deploying remote LED service in swarm

imports:
  - nodetypes/swarm/swarm.yaml
  - nodetypes/service_container/service_container.yaml
  - nodetypes/actuation_service/actuation_service.yaml

metadata:
  template_name: "fog service orchestration"
  template_author: "UoH"
  template_version: "1.0"

topology_template:
  inputs:
    host_ip:
      type: string
      
    managers:
      type: list
      default: []
    workers:
      type: list
      default: []

    actuators:
      type: list
      default: []

  node_templates:
    fog-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    docker-swarm:
      type: fog.nodes.DockerSwarm
      properties:
        managers: { get_input: managers }
        workers: { get_input: workers }
      requirements:
        - host: fog-workstation

    nginx-web-server:
      type: fog.nodes.ServiceContainer
      properties:
        container_name: nginx
        image_name: suvambasak/webpage:websocketled
        published_port: 80
        target_port: 80
        # replicas: 1
      requirements:
        - host: docker-swarm
        - dependency: python-websocket-server

    python-websocket-server:
      type: fog.nodes.ServiceContainer
      properties:
        container_name: websocket_server
        image_name: suvambasak/pyimg:websocketledserver
        published_port: 7890
        target_port: 7890
        # replicas: 1
      requirements:
        - host: docker-swarm

    led-actuators:
      type: fog.nodes.ActuationService
      properties:
        actuators: { get_input: actuators }
      requirements:
        - host: fog-workstation
        - dependency: python-websocket-server
...