---
- hosts: all
  gather_facts: false

  tasks:
    - name: Down service
      docker_compose:
        project_src: /tmp/compose/
        project_name: "{{ name }}"
        state: absent

    - name: Remove the location
      file:
        path: /tmp/compose
        state: absent

    - name: Uninstall prerequsiste Python packages
      pip:
        name:
          - PyYAML >= 3.11
          - docker-compose >= 1.7.0
        state: absent
        executable: pip3
