---
- hosts: all
  gather_facts: false
  tasks:
    # - name: Install prerequsiste Python packages
    #   pip:
    #     name:
    #       - PyYAML >= 3.11
    #       - docker-compose >= 1.7.0
    #     state: latest
    #     executable: pip3

    - name: Install prerequsiste Python packages for Privileged Container
      pip:
        name: "{{ packages }}"
        state: latest
        executable: pip3

    - name: Make the location
      file:
        path: /tmp/compose
        recurse: true
        state: directory

    - name: env file
      copy:
        dest: /tmp/compose/.env
        content: "IP={{ ip_addr }}"

    - name: Download docker-compose file
      get_url:
        url: "{{ url }}"
        dest: /tmp/compose/docker-compose.yaml

    - name: Create and start services
      docker_compose:
        project_src: /tmp/compose/
        project_name: "{{ name }}"
