---
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  radon.nodes.docker:
    derived_from: tosca.nodes.SoftwareComponent

    capabilities:
      host:
        type: tosca.capabilities.Container
        occurrences: [ 1, UNBOUNDED ]
        valid_source_types: [ radon.nodes.container ]

    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create: playbooks/create.yaml
          delete: playbooks/delete.yaml
...