---
- hosts: all
  gather_facts: false
  tasks:
    - name: Make the location
      file:
        path: /tmp/system-service
        recurse: true
        state: directory

    - name: Get python script
      command: "curl -fsSL {{ script_url }} -o /tmp/system-service/{{ script_name }}"

    - name: Get service file Service
      command: "curl -fsSL {{ service_url }} -o /tmp/system-service/{{ service_name }}"

    - name: Move file into system directory
      command: "sudo mv /tmp/system-service/{{ service_name }} /etc/systemd/system/{{ service_name }}"

    - name: Reload the systemctl daemon
      command: "sudo systemctl daemon-reload"

    - name: Enable the service
      command: "sudo systemctl enable {{ service_name }}"

    - name: Start the service
      command: "sudo systemctl start {{ service_name }}"
