---
- hosts: all
  tasks:
    - name: Uninstall Docker packages
      apt:
        name:
          - docker-engine
          - docker
          - docker.io
          - docker-ce
          - docker-ce-cli
          - docker-ce-rootless-extras
        state: absent

    - name: Remove dependencies that are no longer required
      apt:
        autoclean: yes

    - name: Recursively remove docker directory
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /var/lib/docker
        - /etc/apt/sources.list.d/docker.list
    
    - name: Uninstall prerequsiste Python packages
      pip:
        name:
          - docker==5.0.3
        state: absent
        executable: pip3
...