---
tosca_definitions_version: tosca_simple_yaml_1_3

description: Service Template for deploying service container on Docker Swarm.

imports:
  - nodetypes/swarm/swarm.yaml
  - nodetypes/service_container/service_container.yaml

metadata:
  template_name: "docker"
  template_author: "UoH"
  template_version: "1.0"

topology_template:
  inputs:
    host_ip:
      type: string
    
    leader:
      type: string
    managers:
      type: list
      default: []
    workers:
      type: list
      default: []

    replicas:
      type: integer
      default: 1
    port:
      type: integer
      default: 80

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    docker-swarm:
      type: fog.nodes.DockerSwarm
      properties:
        leader: { get_input: leader }
        managers: { get_input: managers }
        workers: { get_input: workers }
      requirements:
        - host: my-workstation

    service-nginx:
      type: fog.nodes.ServiceContainer
      properties:
        port: { get_input: port }
        replicas: { get_input: replicas }
      requirements:
        - host: docker-swarm
...