---
- hosts: all
  gather_facts: false
  tasks:
    - name: Leave a node
      docker_swarm:
        state: absent

    - name: Uninstall prerequsiste Python packages
      pip:
        name:
          - docker==5.0.3
        state: absent
        executable: pip3
