---
- hosts: all
  tasks:
    - name: Install prerequsiste Python packages
      pip:
        name:
          - pip==21.3.1
          - docker==5.0.3
        state: latest
        executable: pip3

    - name: Starting docker service
      service:
        name: docker
        state: started
    
    - name: Init docker swarm
      docker_swarm:
        state: present
      register: token

    - name: saving in file
      shell: echo {{ token.swarm_facts.JoinTokens.Worker }} > /tmp/token
    
    - name: join new node 1 with ssh
      shell: ssh pi@{{ item }} "docker swarm join --token {{ token.swarm_facts.JoinTokens.Worker }} 192.168.0.166:2377"
      loop: "{{ workers }}"

...