---
- hosts: all
  tasks:
    - name: Remove the swarm manager
      docker_swarm:
        state: absent
        force: true
    
    - name: Uninstall prerequsiste Python packages
      pip:
        name:
          - docker==5.0.3
        state: absent
        executable: pip3
...