---
- hosts: all
  tasks:
    - name: Removing worker nodes from swarm
      shell: ssh pi@{{ item }} "docker swarm leave"
      loop: "{{ workers }}"

    - name: Removing manager nodes from swarm
      shell: ssh pi@{{ item }} "docker swarm leave --force"
      loop: "{{ manager }}"

    - name: Removing this node
      docker_swarm:
        state: absent
        force: true
    
    - name: Uninstall prerequsiste Python packages
      pip:
        name:
          - docker==5.0.3
        state: absent
        executable: pip3
...