---
- hosts: all
  tasks:
    - name: Install prerequsiste Python packages
      pip:
        name:
          - pip==21.3.1
          - docker==5.0.3
        state: latest
        executable: pip3

    - name: Starting docker service
      service:
        name: docker
        state: started
    
    - name: Init docker swarm and register the join token
      docker_swarm:
        state: present
      register: token

    - name: Get the IP address of this machine and register
      shell: echo $(hostname -I) | awk '{print $1}'
      register: ip
    
    - name: Join all worker nodes
      shell: ssh pi@{{ item }} "docker swarm join --token {{ token.swarm_facts.JoinTokens.Worker }} {{ ip.stdout }}:2377"
      loop: "{{ workers }}"

    - name: Join all manager nodes
      shell: ssh pi@{{ item }} "docker swarm join --token {{ token.swarm_facts.JoinTokens.Manager }} {{ ip.stdout }}:2377"
      loop: "{{ manager }}"

...