---
tosca_definitions_version: tosca_simple_yaml_1_3

description: Service Template for deploying remote LED in swarm and Priviledged Container on Docker Engine

imports:
  - nodetypes/swarm/swarm.yaml
  - nodetypes/webserver_container/webserver_container.yaml
  - nodetypes/websocket_container/websocket_container.yaml
  - nodetypes/privileged_container/privileged_container.yaml

metadata:
  template_name: "docker"
  template_author: "UoH"
  template_version: "1.0"

topology_template:
  inputs:
    host_ip:
      type: string
      
    manager:
      type: list
      default: []
    workers:
      type: list
      default: []

    privileged_nodes:
      type: list
      default: []

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    docker-swarm:
      type: radon.nodes.DockerSwarm
      requirements:
        - host: my-workstation

    websocket:
      type: radon.nodes.WebsocketContainer
      requirements:
        - host: docker-swarm

    web-server:
      type: radon.nodes.WebserverContainer
      requirements:
        - host: docker-swarm

    privileged-node-led-service:
      type: radon.nodes.PrivilegedContainer
      requirements:
        - host: websocket
...